/*
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFomScopeProvider extends DelegatingScopeProvider {
}
