/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.fom.impl;

import com.cohesionforce.hla.dsl.fom.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FomFactoryImpl extends EFactoryImpl implements FomFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static FomFactory init()
  {
    try
    {
      FomFactory theFomFactory = (FomFactory)EPackage.Registry.INSTANCE.getEFactory(FomPackage.eNS_URI);
      if (theFomFactory != null)
      {
        return theFomFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new FomFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FomFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case FomPackage.FED: return createFed();
      case FomPackage.FEDERATION: return createFederation();
      case FomPackage.FE_DVERSION: return createFEDversion();
      case FomPackage.SPACE: return createSpace();
      case FomPackage.DIMENSION: return createDimension();
      case FomPackage.ATTRIBUTE_CLASS: return createAttributeClass();
      case FomPackage.ATTRIBUTE: return createAttribute();
      case FomPackage.INTERACTION_CLASS: return createInteractionClass();
      case FomPackage.PARAMETER: return createParameter();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fed createFed()
  {
    FedImpl fed = new FedImpl();
    return fed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Federation createFederation()
  {
    FederationImpl federation = new FederationImpl();
    return federation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FEDversion createFEDversion()
  {
    FEDversionImpl feDversion = new FEDversionImpl();
    return feDversion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Space createSpace()
  {
    SpaceImpl space = new SpaceImpl();
    return space;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Dimension createDimension()
  {
    DimensionImpl dimension = new DimensionImpl();
    return dimension;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeClass createAttributeClass()
  {
    AttributeClassImpl attributeClass = new AttributeClassImpl();
    return attributeClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InteractionClass createInteractionClass()
  {
    InteractionClassImpl interactionClass = new InteractionClassImpl();
    return interactionClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parameter createParameter()
  {
    ParameterImpl parameter = new ParameterImpl();
    return parameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FomPackage getFomPackage()
  {
    return (FomPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static FomPackage getPackage()
  {
    return FomPackage.eINSTANCE;
  }

} //FomFactoryImpl
