/*
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.ide.contentassist.antlr;

import com.cohesionforce.hla.dsl.ide.contentassist.antlr.internal.InternalOmtParser;
import com.cohesionforce.hla.dsl.services.OmtGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class OmtParser extends AbstractContentAssistParser {

	@Inject
	private OmtGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalOmtParser createParser() {
		InternalOmtParser result = new InternalOmtParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMOD_TypeAccess().getAlternatives(), "rule__MOD_Type__Alternatives");
					put(grammarAccess.getOMTComponentAccess().getAlternatives(), "rule__OMTComponent__Alternatives");
					put(grammarAccess.getDimensionDomainAccess().getAlternatives(), "rule__DimensionDomain__Alternatives");
					put(grammarAccess.getIntervalTypeAccess().getAlternatives(), "rule__IntervalType__Alternatives");
					put(grammarAccess.getIsMOMClassAccess().getAlternatives(), "rule__IsMOMClass__Alternatives");
					put(grammarAccess.getPSCapabilitiesAccess().getAlternatives(), "rule__PSCapabilities__Alternatives");
					put(grammarAccess.getClassComponentAccess().getAlternatives(), "rule__ClassComponent__Alternatives");
					put(grammarAccess.getATT_UpdateTypeAccess().getAlternatives(), "rule__ATT_UpdateType__Alternatives");
					put(grammarAccess.getATT_TransferAcceptAccess().getAlternatives(), "rule__ATT_TransferAccept__Alternatives");
					put(grammarAccess.getATT_UpdateReflectAccess().getAlternatives(), "rule__ATT_UpdateReflect__Alternatives");
					put(grammarAccess.getEnumeratedDataTypeAccess().getIsMOMEnumeratedDataTypeAlternatives_7_2_0(), "rule__EnumeratedDataType__IsMOMEnumeratedDataTypeAlternatives_7_2_0");
					put(grammarAccess.getComplexDataTypeAccess().getIsMOMComplexDataTypeAlternatives_7_2_0(), "rule__ComplexDataType__IsMOMComplexDataTypeAlternatives_7_2_0");
					put(grammarAccess.getInteractionAccess().getIsMOMInteractionAlternatives_16_2_0(), "rule__Interaction__IsMOMInteractionAlternatives_16_2_0");
					put(grammarAccess.getISRTypeAccess().getAlternatives(), "rule__ISRType__Alternatives");
					put(grammarAccess.getInteractionComponentAccess().getAlternatives(), "rule__InteractionComponent__Alternatives");
					put(grammarAccess.getAnyTextAccess().getAlternatives(), "rule__AnyText__Alternatives");
					put(grammarAccess.getHLAOMT_DIF_v1_3Access().getGroup(), "rule__HLAOMT_DIF_v1_3__Group__0");
					put(grammarAccess.getObjectModelAccess().getGroup(), "rule__ObjectModel__Group__0");
					put(grammarAccess.getObjectModelAccess().getGroup_2(), "rule__ObjectModel__Group_2__0");
					put(grammarAccess.getObjectModelAccess().getGroup_3(), "rule__ObjectModel__Group_3__0");
					put(grammarAccess.getObjectModelAccess().getGroup_4(), "rule__ObjectModel__Group_4__0");
					put(grammarAccess.getObjectModelAccess().getGroup_5(), "rule__ObjectModel__Group_5__0");
					put(grammarAccess.getObjectModelAccess().getGroup_6(), "rule__ObjectModel__Group_6__0");
					put(grammarAccess.getObjectModelAccess().getGroup_7(), "rule__ObjectModel__Group_7__0");
					put(grammarAccess.getObjectModelAccess().getGroup_8(), "rule__ObjectModel__Group_8__0");
					put(grammarAccess.getObjectModelAccess().getGroup_9(), "rule__ObjectModel__Group_9__0");
					put(grammarAccess.getObjectModelAccess().getGroup_10(), "rule__ObjectModel__Group_10__0");
					put(grammarAccess.getObjectModelAccess().getGroup_11(), "rule__ObjectModel__Group_11__0");
					put(grammarAccess.getObjectModelAccess().getGroup_12(), "rule__ObjectModel__Group_12__0");
					put(grammarAccess.getObjectModelAccess().getGroup_13(), "rule__ObjectModel__Group_13__0");
					put(grammarAccess.getObjectModelAccess().getGroup_14(), "rule__ObjectModel__Group_14__0");
					put(grammarAccess.getObjectModelAccess().getGroup_15(), "rule__ObjectModel__Group_15__0");
					put(grammarAccess.getTimeRepresentationAccess().getGroup(), "rule__TimeRepresentation__Group__0");
					put(grammarAccess.getTimeRepresentationAccess().getGroup_27(), "rule__TimeRepresentation__Group_27__0");
					put(grammarAccess.getLookaheadAccess().getGroup(), "rule__Lookahead__Group__0");
					put(grammarAccess.getLookaheadAccess().getGroup_12(), "rule__Lookahead__Group_12__0");
					put(grammarAccess.getRoutingSpaceAccess().getGroup(), "rule__RoutingSpace__Group__0");
					put(grammarAccess.getDimensionAccess().getGroup(), "rule__Dimension__Group__0");
					put(grammarAccess.getDimensionAccess().getGroup_13(), "rule__Dimension__Group_13__0");
					put(grammarAccess.getDimensionRangeAccess().getGroup(), "rule__DimensionRange__Group__0");
					put(grammarAccess.getDimensionRangeAccess().getGroup_5(), "rule__DimensionRange__Group_5__0");
					put(grammarAccess.getDimensionSetAccess().getGroup(), "rule__DimensionSet__Group__0");
					put(grammarAccess.getDimensionSetMemberAccess().getGroup(), "rule__DimensionSetMember__Group__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getClassAccess().getGroup_11(), "rule__Class__Group_11__0");
					put(grammarAccess.getSuperClassAccess().getGroup(), "rule__SuperClass__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_13(), "rule__Attribute__Group_13__0");
					put(grammarAccess.getAttributeAccess().getGroup_14(), "rule__Attribute__Group_14__0");
					put(grammarAccess.getAttributeAccess().getGroup_15(), "rule__Attribute__Group_15__0");
					put(grammarAccess.getAttributeAccess().getGroup_16(), "rule__Attribute__Group_16__0");
					put(grammarAccess.getAttributeAccess().getGroup_18(), "rule__Attribute__Group_18__0");
					put(grammarAccess.getEnumeratedDataTypeAccess().getGroup(), "rule__EnumeratedDataType__Group__0");
					put(grammarAccess.getEnumeratedDataTypeAccess().getGroup_7(), "rule__EnumeratedDataType__Group_7__0");
					put(grammarAccess.getEnumerationAccess().getGroup(), "rule__Enumeration__Group__0");
					put(grammarAccess.getComplexDataTypeAccess().getGroup(), "rule__ComplexDataType__Group__0");
					put(grammarAccess.getComplexDataTypeAccess().getGroup_7(), "rule__ComplexDataType__Group_7__0");
					put(grammarAccess.getComplexComponentAccess().getGroup(), "rule__ComplexComponent__Group__0");
					put(grammarAccess.getAccuracyAccess().getGroup(), "rule__Accuracy__Group__0");
					put(grammarAccess.getAccuracyConditionAccess().getGroup(), "rule__AccuracyCondition__Group__0");
					put(grammarAccess.getResolutionAccess().getGroup(), "rule__Resolution__Group__0");
					put(grammarAccess.getPositionAccess().getGroup(), "rule__Position__Group__0");
					put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
					put(grammarAccess.getFieldNameAccess().getGroup(), "rule__FieldName__Group__0");
					put(grammarAccess.getUnitsAccess().getGroup(), "rule__Units__Group__0");
					put(grammarAccess.getCardinalityAccess().getGroup(), "rule__Cardinality__Group__0");
					put(grammarAccess.getInteractionAccess().getGroup(), "rule__Interaction__Group__0");
					put(grammarAccess.getInteractionAccess().getGroup_16(), "rule__Interaction__Group_16__0");
					put(grammarAccess.getInteractionAccess().getGroup_18(), "rule__Interaction__Group_18__0");
					put(grammarAccess.getSuperInteractionAccess().getGroup(), "rule__SuperInteraction__Group__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
					put(grammarAccess.getNoteAccess().getGroup(), "rule__Note__Group__0");
					put(grammarAccess.getNoteRefAccess().getGroup(), "rule__NoteRef__Group__0");
					put(grammarAccess.getNoteRefAccess().getGroup_2(), "rule__NoteRef__Group_2__0");
					put(grammarAccess.getHLAOMT_DIF_v1_3Access().getNameAssignment_2(), "rule__HLAOMT_DIF_v1_3__NameAssignment_2");
					put(grammarAccess.getHLAOMT_DIF_v1_3Access().getVersionAssignment_3(), "rule__HLAOMT_DIF_v1_3__VersionAssignment_3");
					put(grammarAccess.getHLAOMT_DIF_v1_3Access().getTypeAssignment_6(), "rule__HLAOMT_DIF_v1_3__TypeAssignment_6");
					put(grammarAccess.getHLAOMT_DIF_v1_3Access().getObjectModelsAssignment_9(), "rule__HLAOMT_DIF_v1_3__ObjectModelsAssignment_9");
					put(grammarAccess.getObjectModelAccess().getNameAssignment_2_2(), "rule__ObjectModel__NameAssignment_2_2");
					put(grammarAccess.getObjectModelAccess().getVersionAssignment_3_2(), "rule__ObjectModel__VersionAssignment_3_2");
					put(grammarAccess.getObjectModelAccess().getTypeAssignment_4_2(), "rule__ObjectModel__TypeAssignment_4_2");
					put(grammarAccess.getObjectModelAccess().getPurposeAssignment_5_2(), "rule__ObjectModel__PurposeAssignment_5_2");
					put(grammarAccess.getObjectModelAccess().getDomainAssignment_6_2(), "rule__ObjectModel__DomainAssignment_6_2");
					put(grammarAccess.getObjectModelAccess().getSponsorAssignment_7_2(), "rule__ObjectModel__SponsorAssignment_7_2");
					put(grammarAccess.getObjectModelAccess().getPocHonorificAssignment_8_2(), "rule__ObjectModel__PocHonorificAssignment_8_2");
					put(grammarAccess.getObjectModelAccess().getPocFirstNameAssignment_9_2(), "rule__ObjectModel__PocFirstNameAssignment_9_2");
					put(grammarAccess.getObjectModelAccess().getPocLastNameAssignment_10_2(), "rule__ObjectModel__PocLastNameAssignment_10_2");
					put(grammarAccess.getObjectModelAccess().getPocOrgNameAssignment_11_2(), "rule__ObjectModel__PocOrgNameAssignment_11_2");
					put(grammarAccess.getObjectModelAccess().getPocPhoneAssignment_12_2(), "rule__ObjectModel__PocPhoneAssignment_12_2");
					put(grammarAccess.getObjectModelAccess().getPocEmailAssignment_13_2(), "rule__ObjectModel__PocEmailAssignment_13_2");
					put(grammarAccess.getObjectModelAccess().getModificationDateAssignment_14_2(), "rule__ObjectModel__ModificationDateAssignment_14_2");
					put(grammarAccess.getObjectModelAccess().getMomVersionAssignment_15_2(), "rule__ObjectModel__MomVersionAssignment_15_2");
					put(grammarAccess.getObjectModelAccess().getTimeRepresentationAssignment_16(), "rule__ObjectModel__TimeRepresentationAssignment_16");
					put(grammarAccess.getObjectModelAccess().getLookAheadAssignment_17(), "rule__ObjectModel__LookAheadAssignment_17");
					put(grammarAccess.getObjectModelAccess().getOmtComponentsAssignment_18(), "rule__ObjectModel__OmtComponentsAssignment_18");
					put(grammarAccess.getTimeRepresentationAccess().getUnitsAssignment_4(), "rule__TimeRepresentation__UnitsAssignment_4");
					put(grammarAccess.getTimeRepresentationAccess().getUnitsNoteAssignment_5(), "rule__TimeRepresentation__UnitsNoteAssignment_5");
					put(grammarAccess.getTimeRepresentationAccess().getMinAssignment_9(), "rule__TimeRepresentation__MinAssignment_9");
					put(grammarAccess.getTimeRepresentationAccess().getMinNoteAssignment_10(), "rule__TimeRepresentation__MinNoteAssignment_10");
					put(grammarAccess.getTimeRepresentationAccess().getMaxAssignment_14(), "rule__TimeRepresentation__MaxAssignment_14");
					put(grammarAccess.getTimeRepresentationAccess().getMaxNoteAssignment_15(), "rule__TimeRepresentation__MaxNoteAssignment_15");
					put(grammarAccess.getTimeRepresentationAccess().getInitialAssignment_19(), "rule__TimeRepresentation__InitialAssignment_19");
					put(grammarAccess.getTimeRepresentationAccess().getInitialNoteAssignment_20(), "rule__TimeRepresentation__InitialNoteAssignment_20");
					put(grammarAccess.getTimeRepresentationAccess().getDataTypeAssignment_24(), "rule__TimeRepresentation__DataTypeAssignment_24");
					put(grammarAccess.getTimeRepresentationAccess().getTypeNoteAssignment_25(), "rule__TimeRepresentation__TypeNoteAssignment_25");
					put(grammarAccess.getTimeRepresentationAccess().getOperatorsAssignment_27_2(), "rule__TimeRepresentation__OperatorsAssignment_27_2");
					put(grammarAccess.getTimeRepresentationAccess().getOperatorsNoteAssignment_27_3(), "rule__TimeRepresentation__OperatorsNoteAssignment_27_3");
					put(grammarAccess.getLookaheadAccess().getUnitsAssignment_4(), "rule__Lookahead__UnitsAssignment_4");
					put(grammarAccess.getLookaheadAccess().getUnitsNoteAssignment_5(), "rule__Lookahead__UnitsNoteAssignment_5");
					put(grammarAccess.getLookaheadAccess().getDataTypeAssignment_9(), "rule__Lookahead__DataTypeAssignment_9");
					put(grammarAccess.getLookaheadAccess().getTypeNoteAssignment_10(), "rule__Lookahead__TypeNoteAssignment_10");
					put(grammarAccess.getLookaheadAccess().getOperatorAssignment_12_2(), "rule__Lookahead__OperatorAssignment_12_2");
					put(grammarAccess.getLookaheadAccess().getOperatorNoteAssignment_12_3(), "rule__Lookahead__OperatorNoteAssignment_12_3");
					put(grammarAccess.getRoutingSpaceAccess().getNameAssignment_4(), "rule__RoutingSpace__NameAssignment_4");
					put(grammarAccess.getRoutingSpaceAccess().getNoteAssignment_5(), "rule__RoutingSpace__NoteAssignment_5");
					put(grammarAccess.getRoutingSpaceAccess().getDimensionsAssignment_7(), "rule__RoutingSpace__DimensionsAssignment_7");
					put(grammarAccess.getDimensionAccess().getNameAssignment_4(), "rule__Dimension__NameAssignment_4");
					put(grammarAccess.getDimensionAccess().getNameNoteAssignment_5(), "rule__Dimension__NameNoteAssignment_5");
					put(grammarAccess.getDimensionAccess().getTypeAssignment_9(), "rule__Dimension__TypeAssignment_9");
					put(grammarAccess.getDimensionAccess().getTypeNoteAssignment_10(), "rule__Dimension__TypeNoteAssignment_10");
					put(grammarAccess.getDimensionAccess().getDomainAssignment_12(), "rule__Dimension__DomainAssignment_12");
					put(grammarAccess.getDimensionAccess().getUnitsAssignment_13_2(), "rule__Dimension__UnitsAssignment_13_2");
					put(grammarAccess.getDimensionAccess().getUnitsNoteAssignment_13_3(), "rule__Dimension__UnitsNoteAssignment_13_3");
					put(grammarAccess.getDimensionAccess().getFunctionAssignment_16(), "rule__Dimension__FunctionAssignment_16");
					put(grammarAccess.getDimensionAccess().getFunctionNoteAssignment_17(), "rule__Dimension__FunctionNoteAssignment_17");
					put(grammarAccess.getDimensionRangeAccess().getMinimumAssignment_2(), "rule__DimensionRange__MinimumAssignment_2");
					put(grammarAccess.getDimensionRangeAccess().getNoteAssignment_3(), "rule__DimensionRange__NoteAssignment_3");
					put(grammarAccess.getDimensionRangeAccess().getMaximumAssignment_5_2(), "rule__DimensionRange__MaximumAssignment_5_2");
					put(grammarAccess.getDimensionSetAccess().getMembersAssignment_2(), "rule__DimensionSet__MembersAssignment_2");
					put(grammarAccess.getDimensionSetAccess().getNoteAssignment_3(), "rule__DimensionSet__NoteAssignment_3");
					put(grammarAccess.getDimensionSetMemberAccess().getValueAssignment_2(), "rule__DimensionSetMember__ValueAssignment_2");
					put(grammarAccess.getClassAccess().getIdAssignment_4(), "rule__Class__IdAssignment_4");
					put(grammarAccess.getClassAccess().getNameAssignment_8(), "rule__Class__NameAssignment_8");
					put(grammarAccess.getClassAccess().getNoteAssignment_9(), "rule__Class__NoteAssignment_9");
					put(grammarAccess.getClassAccess().getIsMOMClassAssignment_11_2(), "rule__Class__IsMOMClassAssignment_11_2");
					put(grammarAccess.getClassAccess().getDescriptionAssignment_16(), "rule__Class__DescriptionAssignment_16");
					put(grammarAccess.getClassAccess().getComponentsAssignment_17(), "rule__Class__ComponentsAssignment_17");
					put(grammarAccess.getSuperClassAccess().getSuperClassAssignment_2(), "rule__SuperClass__SuperClassAssignment_2");
					put(grammarAccess.getAttributeAccess().getNameAssignment_4(), "rule__Attribute__NameAssignment_4");
					put(grammarAccess.getAttributeAccess().getNameNoteAssignment_5(), "rule__Attribute__NameNoteAssignment_5");
					put(grammarAccess.getAttributeAccess().getDataTypeAssignment_7(), "rule__Attribute__DataTypeAssignment_7");
					put(grammarAccess.getAttributeAccess().getCardinalityAssignment_8(), "rule__Attribute__CardinalityAssignment_8");
					put(grammarAccess.getAttributeAccess().getUnitsAssignment_9(), "rule__Attribute__UnitsAssignment_9");
					put(grammarAccess.getAttributeAccess().getResolutionAssignment_10(), "rule__Attribute__ResolutionAssignment_10");
					put(grammarAccess.getAttributeAccess().getAccuracyAssignment_11(), "rule__Attribute__AccuracyAssignment_11");
					put(grammarAccess.getAttributeAccess().getAccuracyConditionAssignment_12(), "rule__Attribute__AccuracyConditionAssignment_12");
					put(grammarAccess.getAttributeAccess().getUpdateTypeAssignment_13_2(), "rule__Attribute__UpdateTypeAssignment_13_2");
					put(grammarAccess.getAttributeAccess().getUpdateTypeNoteAssignment_13_3(), "rule__Attribute__UpdateTypeNoteAssignment_13_3");
					put(grammarAccess.getAttributeAccess().getUpdateConditionAssignment_14_2(), "rule__Attribute__UpdateConditionAssignment_14_2");
					put(grammarAccess.getAttributeAccess().getUpdateConditionNoteAssignment_14_3(), "rule__Attribute__UpdateConditionNoteAssignment_14_3");
					put(grammarAccess.getAttributeAccess().getTransferAcceptAssignment_15_2(), "rule__Attribute__TransferAcceptAssignment_15_2");
					put(grammarAccess.getAttributeAccess().getTransferAcceptNoteAssignment_15_3(), "rule__Attribute__TransferAcceptNoteAssignment_15_3");
					put(grammarAccess.getAttributeAccess().getUpdateReflectAssignment_16_2(), "rule__Attribute__UpdateReflectAssignment_16_2");
					put(grammarAccess.getAttributeAccess().getUpdateReflectNoteAssignment_16_3(), "rule__Attribute__UpdateReflectNoteAssignment_16_3");
					put(grammarAccess.getAttributeAccess().getDescriptionAssignment_17(), "rule__Attribute__DescriptionAssignment_17");
					put(grammarAccess.getAttributeAccess().getRoutingSpaceAssignment_18_2(), "rule__Attribute__RoutingSpaceAssignment_18_2");
					put(grammarAccess.getEnumeratedDataTypeAccess().getNameAssignment_4(), "rule__EnumeratedDataType__NameAssignment_4");
					put(grammarAccess.getEnumeratedDataTypeAccess().getNoteAssignment_5(), "rule__EnumeratedDataType__NoteAssignment_5");
					put(grammarAccess.getEnumeratedDataTypeAccess().getIsMOMEnumeratedDataTypeAssignment_7_2(), "rule__EnumeratedDataType__IsMOMEnumeratedDataTypeAssignment_7_2");
					put(grammarAccess.getEnumeratedDataTypeAccess().getLiteralsAssignment_8(), "rule__EnumeratedDataType__LiteralsAssignment_8");
					put(grammarAccess.getEnumerationAccess().getLiteralAssignment_4(), "rule__Enumeration__LiteralAssignment_4");
					put(grammarAccess.getEnumerationAccess().getEnumeratorNoteAssignment_5(), "rule__Enumeration__EnumeratorNoteAssignment_5");
					put(grammarAccess.getEnumerationAccess().getValueAssignment_9(), "rule__Enumeration__ValueAssignment_9");
					put(grammarAccess.getEnumerationAccess().getRepresentationNoteAssignment_10(), "rule__Enumeration__RepresentationNoteAssignment_10");
					put(grammarAccess.getComplexDataTypeAccess().getNameAssignment_4(), "rule__ComplexDataType__NameAssignment_4");
					put(grammarAccess.getComplexDataTypeAccess().getNoteAssignment_5(), "rule__ComplexDataType__NoteAssignment_5");
					put(grammarAccess.getComplexDataTypeAccess().getIsMOMComplexDataTypeAssignment_7_2(), "rule__ComplexDataType__IsMOMComplexDataTypeAssignment_7_2");
					put(grammarAccess.getComplexDataTypeAccess().getComponentsAssignment_8(), "rule__ComplexDataType__ComponentsAssignment_8");
					put(grammarAccess.getComplexComponentAccess().getPositionAssignment_2(), "rule__ComplexComponent__PositionAssignment_2");
					put(grammarAccess.getComplexComponentAccess().getFieldNameAssignment_3(), "rule__ComplexComponent__FieldNameAssignment_3");
					put(grammarAccess.getComplexComponentAccess().getDataTypeAssignment_4(), "rule__ComplexComponent__DataTypeAssignment_4");
					put(grammarAccess.getComplexComponentAccess().getCardinalityAssignment_5(), "rule__ComplexComponent__CardinalityAssignment_5");
					put(grammarAccess.getComplexComponentAccess().getUnitsAssignment_6(), "rule__ComplexComponent__UnitsAssignment_6");
					put(grammarAccess.getComplexComponentAccess().getResolutionAssignment_7(), "rule__ComplexComponent__ResolutionAssignment_7");
					put(grammarAccess.getComplexComponentAccess().getAccuracyAssignment_8(), "rule__ComplexComponent__AccuracyAssignment_8");
					put(grammarAccess.getComplexComponentAccess().getAccuracyConditionAssignment_9(), "rule__ComplexComponent__AccuracyConditionAssignment_9");
					put(grammarAccess.getAccuracyAccess().getAccuracyAssignment_2(), "rule__Accuracy__AccuracyAssignment_2");
					put(grammarAccess.getAccuracyAccess().getAccuracyNoteAssignment_3(), "rule__Accuracy__AccuracyNoteAssignment_3");
					put(grammarAccess.getAccuracyConditionAccess().getAccuracyConditionAssignment_2(), "rule__AccuracyCondition__AccuracyConditionAssignment_2");
					put(grammarAccess.getAccuracyConditionAccess().getAccuracyConditionNoteAssignment_3(), "rule__AccuracyCondition__AccuracyConditionNoteAssignment_3");
					put(grammarAccess.getResolutionAccess().getResolutionAssignment_2(), "rule__Resolution__ResolutionAssignment_2");
					put(grammarAccess.getResolutionAccess().getResolutionNoteAssignment_3(), "rule__Resolution__ResolutionNoteAssignment_3");
					put(grammarAccess.getPositionAccess().getPositionAssignment_2(), "rule__Position__PositionAssignment_2");
					put(grammarAccess.getDataTypeAccess().getDataTypeAssignment_2(), "rule__DataType__DataTypeAssignment_2");
					put(grammarAccess.getDataTypeAccess().getDataTypeNodeAssignment_3(), "rule__DataType__DataTypeNodeAssignment_3");
					put(grammarAccess.getFieldNameAccess().getNameAssignment_2(), "rule__FieldName__NameAssignment_2");
					put(grammarAccess.getFieldNameAccess().getFieldNameNoteAssignment_3(), "rule__FieldName__FieldNameNoteAssignment_3");
					put(grammarAccess.getUnitsAccess().getUnitsAssignment_2(), "rule__Units__UnitsAssignment_2");
					put(grammarAccess.getUnitsAccess().getUnitsNoteAssignment_3(), "rule__Units__UnitsNoteAssignment_3");
					put(grammarAccess.getCardinalityAccess().getCardinalityAssignment_2(), "rule__Cardinality__CardinalityAssignment_2");
					put(grammarAccess.getCardinalityAccess().getCardinalityNoteAssignment_3(), "rule__Cardinality__CardinalityNoteAssignment_3");
					put(grammarAccess.getInteractionAccess().getIdAssignment_4(), "rule__Interaction__IdAssignment_4");
					put(grammarAccess.getInteractionAccess().getNameAssignment_8(), "rule__Interaction__NameAssignment_8");
					put(grammarAccess.getInteractionAccess().getNameNoteAssignment_9(), "rule__Interaction__NameNoteAssignment_9");
					put(grammarAccess.getInteractionAccess().getTypeAssignment_13(), "rule__Interaction__TypeAssignment_13");
					put(grammarAccess.getInteractionAccess().getTypeNoteAssignment_14(), "rule__Interaction__TypeNoteAssignment_14");
					put(grammarAccess.getInteractionAccess().getIsMOMInteractionAssignment_16_2(), "rule__Interaction__IsMOMInteractionAssignment_16_2");
					put(grammarAccess.getInteractionAccess().getDescriptionAssignment_17(), "rule__Interaction__DescriptionAssignment_17");
					put(grammarAccess.getInteractionAccess().getRoutingSpaceAssignment_18_2(), "rule__Interaction__RoutingSpaceAssignment_18_2");
					put(grammarAccess.getInteractionAccess().getComponentsAssignment_19(), "rule__Interaction__ComponentsAssignment_19");
					put(grammarAccess.getSuperInteractionAccess().getIDAssignment_2(), "rule__SuperInteraction__IDAssignment_2");
					put(grammarAccess.getParameterAccess().getNameAssignment_4(), "rule__Parameter__NameAssignment_4");
					put(grammarAccess.getParameterAccess().getNameNoteAssignment_5(), "rule__Parameter__NameNoteAssignment_5");
					put(grammarAccess.getParameterAccess().getDataTypeAssignment_7(), "rule__Parameter__DataTypeAssignment_7");
					put(grammarAccess.getParameterAccess().getCardinalityAssignment_8(), "rule__Parameter__CardinalityAssignment_8");
					put(grammarAccess.getParameterAccess().getUnitsAssignment_9(), "rule__Parameter__UnitsAssignment_9");
					put(grammarAccess.getParameterAccess().getResolutionAssignment_10(), "rule__Parameter__ResolutionAssignment_10");
					put(grammarAccess.getParameterAccess().getAccuracyAssignment_11(), "rule__Parameter__AccuracyAssignment_11");
					put(grammarAccess.getParameterAccess().getAccuracyConditionAssignment_12(), "rule__Parameter__AccuracyConditionAssignment_12");
					put(grammarAccess.getParameterAccess().getDescriptionAssignment_13(), "rule__Parameter__DescriptionAssignment_13");
					put(grammarAccess.getDescriptionAccess().getDescriptionAssignment_2(), "rule__Description__DescriptionAssignment_2");
					put(grammarAccess.getNoteAccess().getIDAssignment_4(), "rule__Note__IDAssignment_4");
					put(grammarAccess.getNoteAccess().getTextAssignment_8(), "rule__Note__TextAssignment_8");
					put(grammarAccess.getNoteRefAccess().getRefsAssignment_1(), "rule__NoteRef__RefsAssignment_1");
					put(grammarAccess.getNoteRefAccess().getRefsAssignment_2_1(), "rule__NoteRef__RefsAssignment_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_COMMENT" };
	}

	public OmtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OmtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
