/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cardinality</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Cardinality#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Cardinality#getCardinalityNote <em>Cardinality Note</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getCardinality()
 * @model
 * @generated
 */
public interface Cardinality extends EObject
{
  /**
   * Returns the value of the '<em><b>Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cardinality</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality</em>' attribute.
   * @see #setCardinality(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getCardinality_Cardinality()
   * @model
   * @generated
   */
  String getCardinality();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Cardinality#getCardinality <em>Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality</em>' attribute.
   * @see #getCardinality()
   * @generated
   */
  void setCardinality(String value);

  /**
   * Returns the value of the '<em><b>Cardinality Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cardinality Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality Note</em>' containment reference.
   * @see #setCardinalityNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getCardinality_CardinalityNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getCardinalityNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Cardinality#getCardinalityNote <em>Cardinality Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality Note</em>' containment reference.
   * @see #getCardinalityNote()
   * @generated
   */
  void setCardinalityNote(NoteRef value);

} // Cardinality
