/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dimension</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getNameNote <em>Name Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getType <em>Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getDataType <em>Data Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getTypeNote <em>Type Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getDomain <em>Domain</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getUnits <em>Units</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getUnitsNote <em>Units Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getFunction <em>Function</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Dimension#getFunctionNote <em>Function Note</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension()
 * @model
 * @generated
 */
public interface Dimension extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Name Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Note</em>' containment reference.
   * @see #setNameNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_NameNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getNameNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getNameNote <em>Name Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Note</em>' containment reference.
   * @see #getNameNote()
   * @generated
   */
  void setNameNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(TypeReference)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_Type()
   * @model
   * @generated
   */
  TypeReference getType();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(TypeReference value);

  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see #setDataType(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_DataType()
   * @model
   * @generated
   */
  String getDataType();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see #getDataType()
   * @generated
   */
  void setDataType(String value);

  /**
   * Returns the value of the '<em><b>Type Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Note</em>' containment reference.
   * @see #setTypeNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_TypeNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getTypeNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getTypeNote <em>Type Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Note</em>' containment reference.
   * @see #getTypeNote()
   * @generated
   */
  void setTypeNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Domain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Domain</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain</em>' containment reference.
   * @see #setDomain(DimensionDomain)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_Domain()
   * @model containment="true"
   * @generated
   */
  DimensionDomain getDomain();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getDomain <em>Domain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain</em>' containment reference.
   * @see #getDomain()
   * @generated
   */
  void setDomain(DimensionDomain value);

  /**
   * Returns the value of the '<em><b>Units</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Units</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' attribute.
   * @see #setUnits(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_Units()
   * @model
   * @generated
   */
  String getUnits();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getUnits <em>Units</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Units</em>' attribute.
   * @see #getUnits()
   * @generated
   */
  void setUnits(String value);

  /**
   * Returns the value of the '<em><b>Units Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Units Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units Note</em>' containment reference.
   * @see #setUnitsNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_UnitsNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getUnitsNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getUnitsNote <em>Units Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Units Note</em>' containment reference.
   * @see #getUnitsNote()
   * @generated
   */
  void setUnitsNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

  /**
   * Returns the value of the '<em><b>Function Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Note</em>' containment reference.
   * @see #setFunctionNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getDimension_FunctionNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getFunctionNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Dimension#getFunctionNote <em>Function Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Note</em>' containment reference.
   * @see #getFunctionNote()
   * @generated
   */
  void setFunctionNote(NoteRef value);

} // Dimension
