/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Enumeration#getLiteral <em>Literal</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Enumeration#getEnumeratorNote <em>Enumerator Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Enumeration#getValue <em>Value</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Enumeration#getRepresentationNote <em>Representation Note</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getEnumeration()
 * @model
 * @generated
 */
public interface Enumeration extends EObject
{
  /**
   * Returns the value of the '<em><b>Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Literal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' attribute.
   * @see #setLiteral(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getEnumeration_Literal()
   * @model
   * @generated
   */
  String getLiteral();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Enumeration#getLiteral <em>Literal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' attribute.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(String value);

  /**
   * Returns the value of the '<em><b>Enumerator Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumerator Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumerator Note</em>' containment reference.
   * @see #setEnumeratorNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getEnumeration_EnumeratorNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getEnumeratorNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Enumeration#getEnumeratorNote <em>Enumerator Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumerator Note</em>' containment reference.
   * @see #getEnumeratorNote()
   * @generated
   */
  void setEnumeratorNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getEnumeration_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Enumeration#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Representation Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Representation Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Representation Note</em>' containment reference.
   * @see #setRepresentationNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getEnumeration_RepresentationNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getRepresentationNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Enumeration#getRepresentationNote <em>Representation Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Representation Note</em>' containment reference.
   * @see #getRepresentationNote()
   * @generated
   */
  void setRepresentationNote(NoteRef value);

} // Enumeration
