/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getId <em>Id</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getNameNote <em>Name Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getType <em>Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getTypeNote <em>Type Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getIsMOMInteraction <em>Is MOM Interaction</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getDescription <em>Description</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getRoutingSpace <em>Routing Space</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Interaction#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction()
 * @model
 * @generated
 */
public interface Interaction extends OMTComponent
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Name Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Note</em>' containment reference.
   * @see #setNameNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_NameNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getNameNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getNameNote <em>Name Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Note</em>' containment reference.
   * @see #getNameNote()
   * @generated
   */
  void setNameNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Type Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Note</em>' containment reference.
   * @see #setTypeNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_TypeNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getTypeNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getTypeNote <em>Type Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Note</em>' containment reference.
   * @see #getTypeNote()
   * @generated
   */
  void setTypeNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Is MOM Interaction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is MOM Interaction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is MOM Interaction</em>' attribute.
   * @see #setIsMOMInteraction(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_IsMOMInteraction()
   * @model
   * @generated
   */
  String getIsMOMInteraction();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getIsMOMInteraction <em>Is MOM Interaction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is MOM Interaction</em>' attribute.
   * @see #getIsMOMInteraction()
   * @generated
   */
  void setIsMOMInteraction(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference list.
   * The list contents are of type {@link com.cohesionforce.hla.dsl.omt.Description}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference list.
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_Description()
   * @model containment="true"
   * @generated
   */
  EList<Description> getDescription();

  /**
   * Returns the value of the '<em><b>Routing Space</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Routing Space</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Routing Space</em>' reference.
   * @see #setRoutingSpace(RoutingSpace)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_RoutingSpace()
   * @model
   * @generated
   */
  RoutingSpace getRoutingSpace();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Interaction#getRoutingSpace <em>Routing Space</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Routing Space</em>' reference.
   * @see #getRoutingSpace()
   * @generated
   */
  void setRoutingSpace(RoutingSpace value);

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link com.cohesionforce.hla.dsl.omt.InteractionComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getInteraction_Components()
   * @model containment="true"
   * @generated
   */
  EList<InteractionComponent> getComponents();

} // Interaction
