/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lookahead</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Lookahead#getUnits <em>Units</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Lookahead#getUnitsNote <em>Units Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Lookahead#getDataType <em>Data Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Lookahead#getTypeNote <em>Type Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Lookahead#getOperator <em>Operator</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Lookahead#getOperatorNote <em>Operator Note</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead()
 * @model
 * @generated
 */
public interface Lookahead extends EObject
{
  /**
   * Returns the value of the '<em><b>Units</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Units</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' attribute.
   * @see #setUnits(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead_Units()
   * @model
   * @generated
   */
  String getUnits();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Lookahead#getUnits <em>Units</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Units</em>' attribute.
   * @see #getUnits()
   * @generated
   */
  void setUnits(String value);

  /**
   * Returns the value of the '<em><b>Units Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Units Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units Note</em>' containment reference.
   * @see #setUnitsNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead_UnitsNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getUnitsNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Lookahead#getUnitsNote <em>Units Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Units Note</em>' containment reference.
   * @see #getUnitsNote()
   * @generated
   */
  void setUnitsNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see #setDataType(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead_DataType()
   * @model
   * @generated
   */
  String getDataType();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Lookahead#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see #getDataType()
   * @generated
   */
  void setDataType(String value);

  /**
   * Returns the value of the '<em><b>Type Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Note</em>' containment reference.
   * @see #setTypeNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead_TypeNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getTypeNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Lookahead#getTypeNote <em>Type Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Note</em>' containment reference.
   * @see #getTypeNote()
   * @generated
   */
  void setTypeNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Lookahead#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Operator Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator Note</em>' containment reference.
   * @see #setOperatorNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getLookahead_OperatorNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getOperatorNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Lookahead#getOperatorNote <em>Operator Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator Note</em>' containment reference.
   * @see #getOperatorNote()
   * @generated
   */
  void setOperatorNote(NoteRef value);

} // Lookahead
