/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OMT Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getOMTComponent()
 * @model
 * @generated
 */
public interface OMTComponent extends EObject
{
} // OMTComponent
