/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resolution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Resolution#getResolution <em>Resolution</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.Resolution#getResolutionNote <em>Resolution Note</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getResolution()
 * @model
 * @generated
 */
public interface Resolution extends EObject
{
  /**
   * Returns the value of the '<em><b>Resolution</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resolution</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resolution</em>' attribute.
   * @see #setResolution(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getResolution_Resolution()
   * @model
   * @generated
   */
  String getResolution();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Resolution#getResolution <em>Resolution</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resolution</em>' attribute.
   * @see #getResolution()
   * @generated
   */
  void setResolution(String value);

  /**
   * Returns the value of the '<em><b>Resolution Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resolution Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resolution Note</em>' containment reference.
   * @see #setResolutionNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getResolution_ResolutionNote()
   * @model containment="true"
   * @generated
   */
  NoteRef getResolutionNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.Resolution#getResolutionNote <em>Resolution Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resolution Note</em>' containment reference.
   * @see #getResolutionNote()
   * @generated
   */
  void setResolutionNote(NoteRef value);

} // Resolution
