/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Routing Space</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.RoutingSpace#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.RoutingSpace#getNote <em>Note</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.RoutingSpace#getDimensions <em>Dimensions</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getRoutingSpace()
 * @model
 * @generated
 */
public interface RoutingSpace extends OMTComponent
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getRoutingSpace_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.RoutingSpace#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Note</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note</em>' containment reference.
   * @see #setNote(NoteRef)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getRoutingSpace_Note()
   * @model containment="true"
   * @generated
   */
  NoteRef getNote();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.RoutingSpace#getNote <em>Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Note</em>' containment reference.
   * @see #getNote()
   * @generated
   */
  void setNote(NoteRef value);

  /**
   * Returns the value of the '<em><b>Dimensions</b></em>' containment reference list.
   * The list contents are of type {@link com.cohesionforce.hla.dsl.omt.Dimension}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dimensions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimensions</em>' containment reference list.
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getRoutingSpace_Dimensions()
   * @model containment="true"
   * @generated
   */
  EList<Dimension> getDimensions();

} // RoutingSpace
