/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Super Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.SuperInteraction#getID <em>ID</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getSuperInteraction()
 * @model
 * @generated
 */
public interface SuperInteraction extends InteractionComponent
{
  /**
   * Returns the value of the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' attribute.
   * @see #setID(int)
   * @see com.cohesionforce.hla.dsl.omt.OmtPackage#getSuperInteraction_ID()
   * @model
   * @generated
   */
  int getID();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.omt.SuperInteraction#getID <em>ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' attribute.
   * @see #getID()
   * @generated
   */
  void setID(int value);

} // SuperInteraction
