/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt.impl;

import com.cohesionforce.hla.dsl.omt.Accuracy;
import com.cohesionforce.hla.dsl.omt.AccuracyCondition;
import com.cohesionforce.hla.dsl.omt.Cardinality;
import com.cohesionforce.hla.dsl.omt.ComplexComponent;
import com.cohesionforce.hla.dsl.omt.DataType;
import com.cohesionforce.hla.dsl.omt.FieldName;
import com.cohesionforce.hla.dsl.omt.OmtPackage;
import com.cohesionforce.hla.dsl.omt.Position;
import com.cohesionforce.hla.dsl.omt.Resolution;
import com.cohesionforce.hla.dsl.omt.Units;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex Component</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getPosition <em>Position</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getFieldName <em>Field Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getDataType <em>Data Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getUnits <em>Units</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getResolution <em>Resolution</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getAccuracy <em>Accuracy</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ComplexComponentImpl#getAccuracyCondition <em>Accuracy Condition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComplexComponentImpl extends MinimalEObjectImpl.Container implements ComplexComponent
{
  /**
   * The cached value of the '{@link #getPosition() <em>Position</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosition()
   * @generated
   * @ordered
   */
  protected Position position;

  /**
   * The cached value of the '{@link #getFieldName() <em>Field Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldName()
   * @generated
   * @ordered
   */
  protected FieldName fieldName;

  /**
   * The cached value of the '{@link #getDataType() <em>Data Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataType()
   * @generated
   * @ordered
   */
  protected DataType dataType;

  /**
   * The cached value of the '{@link #getCardinality() <em>Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCardinality()
   * @generated
   * @ordered
   */
  protected Cardinality cardinality;

  /**
   * The cached value of the '{@link #getUnits() <em>Units</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnits()
   * @generated
   * @ordered
   */
  protected Units units;

  /**
   * The cached value of the '{@link #getResolution() <em>Resolution</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResolution()
   * @generated
   * @ordered
   */
  protected Resolution resolution;

  /**
   * The cached value of the '{@link #getAccuracy() <em>Accuracy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccuracy()
   * @generated
   * @ordered
   */
  protected Accuracy accuracy;

  /**
   * The cached value of the '{@link #getAccuracyCondition() <em>Accuracy Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccuracyCondition()
   * @generated
   * @ordered
   */
  protected AccuracyCondition accuracyCondition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OmtPackage.Literals.COMPLEX_COMPONENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Position getPosition()
  {
    return position;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPosition(Position newPosition, NotificationChain msgs)
  {
    Position oldPosition = position;
    position = newPosition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__POSITION, oldPosition, newPosition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPosition(Position newPosition)
  {
    if (newPosition != position)
    {
      NotificationChain msgs = null;
      if (position != null)
        msgs = ((InternalEObject)position).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__POSITION, null, msgs);
      if (newPosition != null)
        msgs = ((InternalEObject)newPosition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__POSITION, null, msgs);
      msgs = basicSetPosition(newPosition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__POSITION, newPosition, newPosition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FieldName getFieldName()
  {
    return fieldName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFieldName(FieldName newFieldName, NotificationChain msgs)
  {
    FieldName oldFieldName = fieldName;
    fieldName = newFieldName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__FIELD_NAME, oldFieldName, newFieldName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFieldName(FieldName newFieldName)
  {
    if (newFieldName != fieldName)
    {
      NotificationChain msgs = null;
      if (fieldName != null)
        msgs = ((InternalEObject)fieldName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__FIELD_NAME, null, msgs);
      if (newFieldName != null)
        msgs = ((InternalEObject)newFieldName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__FIELD_NAME, null, msgs);
      msgs = basicSetFieldName(newFieldName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__FIELD_NAME, newFieldName, newFieldName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType getDataType()
  {
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDataType(DataType newDataType, NotificationChain msgs)
  {
    DataType oldDataType = dataType;
    dataType = newDataType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__DATA_TYPE, oldDataType, newDataType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDataType(DataType newDataType)
  {
    if (newDataType != dataType)
    {
      NotificationChain msgs = null;
      if (dataType != null)
        msgs = ((InternalEObject)dataType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__DATA_TYPE, null, msgs);
      if (newDataType != null)
        msgs = ((InternalEObject)newDataType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__DATA_TYPE, null, msgs);
      msgs = basicSetDataType(newDataType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__DATA_TYPE, newDataType, newDataType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Cardinality getCardinality()
  {
    return cardinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCardinality(Cardinality newCardinality, NotificationChain msgs)
  {
    Cardinality oldCardinality = cardinality;
    cardinality = newCardinality;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__CARDINALITY, oldCardinality, newCardinality);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCardinality(Cardinality newCardinality)
  {
    if (newCardinality != cardinality)
    {
      NotificationChain msgs = null;
      if (cardinality != null)
        msgs = ((InternalEObject)cardinality).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__CARDINALITY, null, msgs);
      if (newCardinality != null)
        msgs = ((InternalEObject)newCardinality).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__CARDINALITY, null, msgs);
      msgs = basicSetCardinality(newCardinality, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__CARDINALITY, newCardinality, newCardinality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Units getUnits()
  {
    return units;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUnits(Units newUnits, NotificationChain msgs)
  {
    Units oldUnits = units;
    units = newUnits;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__UNITS, oldUnits, newUnits);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnits(Units newUnits)
  {
    if (newUnits != units)
    {
      NotificationChain msgs = null;
      if (units != null)
        msgs = ((InternalEObject)units).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__UNITS, null, msgs);
      if (newUnits != null)
        msgs = ((InternalEObject)newUnits).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__UNITS, null, msgs);
      msgs = basicSetUnits(newUnits, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__UNITS, newUnits, newUnits));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Resolution getResolution()
  {
    return resolution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResolution(Resolution newResolution, NotificationChain msgs)
  {
    Resolution oldResolution = resolution;
    resolution = newResolution;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__RESOLUTION, oldResolution, newResolution);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setResolution(Resolution newResolution)
  {
    if (newResolution != resolution)
    {
      NotificationChain msgs = null;
      if (resolution != null)
        msgs = ((InternalEObject)resolution).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__RESOLUTION, null, msgs);
      if (newResolution != null)
        msgs = ((InternalEObject)newResolution).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__RESOLUTION, null, msgs);
      msgs = basicSetResolution(newResolution, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__RESOLUTION, newResolution, newResolution));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Accuracy getAccuracy()
  {
    return accuracy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAccuracy(Accuracy newAccuracy, NotificationChain msgs)
  {
    Accuracy oldAccuracy = accuracy;
    accuracy = newAccuracy;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__ACCURACY, oldAccuracy, newAccuracy);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAccuracy(Accuracy newAccuracy)
  {
    if (newAccuracy != accuracy)
    {
      NotificationChain msgs = null;
      if (accuracy != null)
        msgs = ((InternalEObject)accuracy).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__ACCURACY, null, msgs);
      if (newAccuracy != null)
        msgs = ((InternalEObject)newAccuracy).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__ACCURACY, null, msgs);
      msgs = basicSetAccuracy(newAccuracy, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__ACCURACY, newAccuracy, newAccuracy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AccuracyCondition getAccuracyCondition()
  {
    return accuracyCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAccuracyCondition(AccuracyCondition newAccuracyCondition, NotificationChain msgs)
  {
    AccuracyCondition oldAccuracyCondition = accuracyCondition;
    accuracyCondition = newAccuracyCondition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION, oldAccuracyCondition, newAccuracyCondition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAccuracyCondition(AccuracyCondition newAccuracyCondition)
  {
    if (newAccuracyCondition != accuracyCondition)
    {
      NotificationChain msgs = null;
      if (accuracyCondition != null)
        msgs = ((InternalEObject)accuracyCondition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION, null, msgs);
      if (newAccuracyCondition != null)
        msgs = ((InternalEObject)newAccuracyCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION, null, msgs);
      msgs = basicSetAccuracyCondition(newAccuracyCondition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION, newAccuracyCondition, newAccuracyCondition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OmtPackage.COMPLEX_COMPONENT__POSITION:
        return basicSetPosition(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__FIELD_NAME:
        return basicSetFieldName(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__DATA_TYPE:
        return basicSetDataType(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__CARDINALITY:
        return basicSetCardinality(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__UNITS:
        return basicSetUnits(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__RESOLUTION:
        return basicSetResolution(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY:
        return basicSetAccuracy(null, msgs);
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION:
        return basicSetAccuracyCondition(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OmtPackage.COMPLEX_COMPONENT__POSITION:
        return getPosition();
      case OmtPackage.COMPLEX_COMPONENT__FIELD_NAME:
        return getFieldName();
      case OmtPackage.COMPLEX_COMPONENT__DATA_TYPE:
        return getDataType();
      case OmtPackage.COMPLEX_COMPONENT__CARDINALITY:
        return getCardinality();
      case OmtPackage.COMPLEX_COMPONENT__UNITS:
        return getUnits();
      case OmtPackage.COMPLEX_COMPONENT__RESOLUTION:
        return getResolution();
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY:
        return getAccuracy();
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION:
        return getAccuracyCondition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OmtPackage.COMPLEX_COMPONENT__POSITION:
        setPosition((Position)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__FIELD_NAME:
        setFieldName((FieldName)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__DATA_TYPE:
        setDataType((DataType)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__CARDINALITY:
        setCardinality((Cardinality)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__UNITS:
        setUnits((Units)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__RESOLUTION:
        setResolution((Resolution)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY:
        setAccuracy((Accuracy)newValue);
        return;
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION:
        setAccuracyCondition((AccuracyCondition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OmtPackage.COMPLEX_COMPONENT__POSITION:
        setPosition((Position)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__FIELD_NAME:
        setFieldName((FieldName)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__DATA_TYPE:
        setDataType((DataType)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__CARDINALITY:
        setCardinality((Cardinality)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__UNITS:
        setUnits((Units)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__RESOLUTION:
        setResolution((Resolution)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY:
        setAccuracy((Accuracy)null);
        return;
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION:
        setAccuracyCondition((AccuracyCondition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OmtPackage.COMPLEX_COMPONENT__POSITION:
        return position != null;
      case OmtPackage.COMPLEX_COMPONENT__FIELD_NAME:
        return fieldName != null;
      case OmtPackage.COMPLEX_COMPONENT__DATA_TYPE:
        return dataType != null;
      case OmtPackage.COMPLEX_COMPONENT__CARDINALITY:
        return cardinality != null;
      case OmtPackage.COMPLEX_COMPONENT__UNITS:
        return units != null;
      case OmtPackage.COMPLEX_COMPONENT__RESOLUTION:
        return resolution != null;
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY:
        return accuracy != null;
      case OmtPackage.COMPLEX_COMPONENT__ACCURACY_CONDITION:
        return accuracyCondition != null;
    }
    return super.eIsSet(featureID);
  }

} //ComplexComponentImpl
