/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt.impl;

import com.cohesionforce.hla.dsl.omt.HLAOMT_DIF_v1_3;
import com.cohesionforce.hla.dsl.omt.ObjectModel;
import com.cohesionforce.hla.dsl.omt.OmtPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>HLAOMT DIF v1 3</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.HLAOMT_DIF_v1_3Impl#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.HLAOMT_DIF_v1_3Impl#getVersion <em>Version</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.HLAOMT_DIF_v1_3Impl#getType <em>Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.HLAOMT_DIF_v1_3Impl#getObjectModels <em>Object Models</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HLAOMT_DIF_v1_3Impl extends MinimalEObjectImpl.Container implements HLAOMT_DIF_v1_3
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected static final String VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected String version = VERSION_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getObjectModels() <em>Object Models</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjectModels()
   * @generated
   * @ordered
   */
  protected EList<ObjectModel> objectModels;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HLAOMT_DIF_v1_3Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OmtPackage.Literals.HLAOMT_DIF_V1_3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.HLAOMT_DIF_V1_3__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVersion()
  {
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVersion(String newVersion)
  {
    String oldVersion = version;
    version = newVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.HLAOMT_DIF_V1_3__VERSION, oldVersion, version));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.HLAOMT_DIF_V1_3__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ObjectModel> getObjectModels()
  {
    if (objectModels == null)
    {
      objectModels = new EObjectContainmentEList<ObjectModel>(ObjectModel.class, this, OmtPackage.HLAOMT_DIF_V1_3__OBJECT_MODELS);
    }
    return objectModels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OmtPackage.HLAOMT_DIF_V1_3__OBJECT_MODELS:
        return ((InternalEList<?>)getObjectModels()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OmtPackage.HLAOMT_DIF_V1_3__NAME:
        return getName();
      case OmtPackage.HLAOMT_DIF_V1_3__VERSION:
        return getVersion();
      case OmtPackage.HLAOMT_DIF_V1_3__TYPE:
        return getType();
      case OmtPackage.HLAOMT_DIF_V1_3__OBJECT_MODELS:
        return getObjectModels();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OmtPackage.HLAOMT_DIF_V1_3__NAME:
        setName((String)newValue);
        return;
      case OmtPackage.HLAOMT_DIF_V1_3__VERSION:
        setVersion((String)newValue);
        return;
      case OmtPackage.HLAOMT_DIF_V1_3__TYPE:
        setType((String)newValue);
        return;
      case OmtPackage.HLAOMT_DIF_V1_3__OBJECT_MODELS:
        getObjectModels().clear();
        getObjectModels().addAll((Collection<? extends ObjectModel>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OmtPackage.HLAOMT_DIF_V1_3__NAME:
        setName(NAME_EDEFAULT);
        return;
      case OmtPackage.HLAOMT_DIF_V1_3__VERSION:
        setVersion(VERSION_EDEFAULT);
        return;
      case OmtPackage.HLAOMT_DIF_V1_3__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case OmtPackage.HLAOMT_DIF_V1_3__OBJECT_MODELS:
        getObjectModels().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OmtPackage.HLAOMT_DIF_V1_3__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case OmtPackage.HLAOMT_DIF_V1_3__VERSION:
        return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
      case OmtPackage.HLAOMT_DIF_V1_3__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case OmtPackage.HLAOMT_DIF_V1_3__OBJECT_MODELS:
        return objectModels != null && !objectModels.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", version: ");
    result.append(version);
    result.append(", type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //HLAOMT_DIF_v1_3Impl
