/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.omt.impl;

import com.cohesionforce.hla.dsl.omt.Lookahead;
import com.cohesionforce.hla.dsl.omt.OMTComponent;
import com.cohesionforce.hla.dsl.omt.ObjectModel;
import com.cohesionforce.hla.dsl.omt.OmtPackage;
import com.cohesionforce.hla.dsl.omt.TimeRepresentation;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getType <em>Type</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPurpose <em>Purpose</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getDomain <em>Domain</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getSponsor <em>Sponsor</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPocHonorific <em>Poc Honorific</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPocFirstName <em>Poc First Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPocLastName <em>Poc Last Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPocOrgName <em>Poc Org Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPocPhone <em>Poc Phone</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getPocEmail <em>Poc Email</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getModificationDate <em>Modification Date</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getMomVersion <em>Mom Version</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getTimeRepresentation <em>Time Representation</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getLookAhead <em>Look Ahead</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.omt.impl.ObjectModelImpl#getOmtComponents <em>Omt Components</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectModelImpl extends MinimalEObjectImpl.Container implements ObjectModel
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected static final String VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected String version = VERSION_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getPurpose() <em>Purpose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPurpose()
   * @generated
   * @ordered
   */
  protected static final String PURPOSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPurpose() <em>Purpose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPurpose()
   * @generated
   * @ordered
   */
  protected String purpose = PURPOSE_EDEFAULT;

  /**
   * The default value of the '{@link #getDomain() <em>Domain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDomain()
   * @generated
   * @ordered
   */
  protected static final String DOMAIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDomain() <em>Domain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDomain()
   * @generated
   * @ordered
   */
  protected String domain = DOMAIN_EDEFAULT;

  /**
   * The default value of the '{@link #getSponsor() <em>Sponsor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSponsor()
   * @generated
   * @ordered
   */
  protected static final String SPONSOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSponsor() <em>Sponsor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSponsor()
   * @generated
   * @ordered
   */
  protected String sponsor = SPONSOR_EDEFAULT;

  /**
   * The default value of the '{@link #getPocHonorific() <em>Poc Honorific</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocHonorific()
   * @generated
   * @ordered
   */
  protected static final String POC_HONORIFIC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPocHonorific() <em>Poc Honorific</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocHonorific()
   * @generated
   * @ordered
   */
  protected String pocHonorific = POC_HONORIFIC_EDEFAULT;

  /**
   * The default value of the '{@link #getPocFirstName() <em>Poc First Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocFirstName()
   * @generated
   * @ordered
   */
  protected static final String POC_FIRST_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPocFirstName() <em>Poc First Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocFirstName()
   * @generated
   * @ordered
   */
  protected String pocFirstName = POC_FIRST_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPocLastName() <em>Poc Last Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocLastName()
   * @generated
   * @ordered
   */
  protected static final String POC_LAST_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPocLastName() <em>Poc Last Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocLastName()
   * @generated
   * @ordered
   */
  protected String pocLastName = POC_LAST_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPocOrgName() <em>Poc Org Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocOrgName()
   * @generated
   * @ordered
   */
  protected static final String POC_ORG_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPocOrgName() <em>Poc Org Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocOrgName()
   * @generated
   * @ordered
   */
  protected String pocOrgName = POC_ORG_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPocPhone() <em>Poc Phone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocPhone()
   * @generated
   * @ordered
   */
  protected static final String POC_PHONE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPocPhone() <em>Poc Phone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocPhone()
   * @generated
   * @ordered
   */
  protected String pocPhone = POC_PHONE_EDEFAULT;

  /**
   * The default value of the '{@link #getPocEmail() <em>Poc Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocEmail()
   * @generated
   * @ordered
   */
  protected static final String POC_EMAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPocEmail() <em>Poc Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPocEmail()
   * @generated
   * @ordered
   */
  protected String pocEmail = POC_EMAIL_EDEFAULT;

  /**
   * The default value of the '{@link #getModificationDate() <em>Modification Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModificationDate()
   * @generated
   * @ordered
   */
  protected static final String MODIFICATION_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModificationDate() <em>Modification Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModificationDate()
   * @generated
   * @ordered
   */
  protected String modificationDate = MODIFICATION_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getMomVersion() <em>Mom Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMomVersion()
   * @generated
   * @ordered
   */
  protected static final String MOM_VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMomVersion() <em>Mom Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMomVersion()
   * @generated
   * @ordered
   */
  protected String momVersion = MOM_VERSION_EDEFAULT;

  /**
   * The cached value of the '{@link #getTimeRepresentation() <em>Time Representation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeRepresentation()
   * @generated
   * @ordered
   */
  protected TimeRepresentation timeRepresentation;

  /**
   * The cached value of the '{@link #getLookAhead() <em>Look Ahead</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLookAhead()
   * @generated
   * @ordered
   */
  protected Lookahead lookAhead;

  /**
   * The cached value of the '{@link #getOmtComponents() <em>Omt Components</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOmtComponents()
   * @generated
   * @ordered
   */
  protected EList<OMTComponent> omtComponents;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OmtPackage.Literals.OBJECT_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVersion()
  {
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVersion(String newVersion)
  {
    String oldVersion = version;
    version = newVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__VERSION, oldVersion, version));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPurpose()
  {
    return purpose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPurpose(String newPurpose)
  {
    String oldPurpose = purpose;
    purpose = newPurpose;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__PURPOSE, oldPurpose, purpose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDomain()
  {
    return domain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDomain(String newDomain)
  {
    String oldDomain = domain;
    domain = newDomain;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__DOMAIN, oldDomain, domain));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSponsor()
  {
    return sponsor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSponsor(String newSponsor)
  {
    String oldSponsor = sponsor;
    sponsor = newSponsor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__SPONSOR, oldSponsor, sponsor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPocHonorific()
  {
    return pocHonorific;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPocHonorific(String newPocHonorific)
  {
    String oldPocHonorific = pocHonorific;
    pocHonorific = newPocHonorific;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__POC_HONORIFIC, oldPocHonorific, pocHonorific));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPocFirstName()
  {
    return pocFirstName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPocFirstName(String newPocFirstName)
  {
    String oldPocFirstName = pocFirstName;
    pocFirstName = newPocFirstName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__POC_FIRST_NAME, oldPocFirstName, pocFirstName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPocLastName()
  {
    return pocLastName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPocLastName(String newPocLastName)
  {
    String oldPocLastName = pocLastName;
    pocLastName = newPocLastName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__POC_LAST_NAME, oldPocLastName, pocLastName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPocOrgName()
  {
    return pocOrgName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPocOrgName(String newPocOrgName)
  {
    String oldPocOrgName = pocOrgName;
    pocOrgName = newPocOrgName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__POC_ORG_NAME, oldPocOrgName, pocOrgName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPocPhone()
  {
    return pocPhone;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPocPhone(String newPocPhone)
  {
    String oldPocPhone = pocPhone;
    pocPhone = newPocPhone;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__POC_PHONE, oldPocPhone, pocPhone));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPocEmail()
  {
    return pocEmail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPocEmail(String newPocEmail)
  {
    String oldPocEmail = pocEmail;
    pocEmail = newPocEmail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__POC_EMAIL, oldPocEmail, pocEmail));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getModificationDate()
  {
    return modificationDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setModificationDate(String newModificationDate)
  {
    String oldModificationDate = modificationDate;
    modificationDate = newModificationDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__MODIFICATION_DATE, oldModificationDate, modificationDate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMomVersion()
  {
    return momVersion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMomVersion(String newMomVersion)
  {
    String oldMomVersion = momVersion;
    momVersion = newMomVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__MOM_VERSION, oldMomVersion, momVersion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TimeRepresentation getTimeRepresentation()
  {
    return timeRepresentation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTimeRepresentation(TimeRepresentation newTimeRepresentation, NotificationChain msgs)
  {
    TimeRepresentation oldTimeRepresentation = timeRepresentation;
    timeRepresentation = newTimeRepresentation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION, oldTimeRepresentation, newTimeRepresentation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTimeRepresentation(TimeRepresentation newTimeRepresentation)
  {
    if (newTimeRepresentation != timeRepresentation)
    {
      NotificationChain msgs = null;
      if (timeRepresentation != null)
        msgs = ((InternalEObject)timeRepresentation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION, null, msgs);
      if (newTimeRepresentation != null)
        msgs = ((InternalEObject)newTimeRepresentation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION, null, msgs);
      msgs = basicSetTimeRepresentation(newTimeRepresentation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION, newTimeRepresentation, newTimeRepresentation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lookahead getLookAhead()
  {
    return lookAhead;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLookAhead(Lookahead newLookAhead, NotificationChain msgs)
  {
    Lookahead oldLookAhead = lookAhead;
    lookAhead = newLookAhead;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__LOOK_AHEAD, oldLookAhead, newLookAhead);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLookAhead(Lookahead newLookAhead)
  {
    if (newLookAhead != lookAhead)
    {
      NotificationChain msgs = null;
      if (lookAhead != null)
        msgs = ((InternalEObject)lookAhead).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OmtPackage.OBJECT_MODEL__LOOK_AHEAD, null, msgs);
      if (newLookAhead != null)
        msgs = ((InternalEObject)newLookAhead).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OmtPackage.OBJECT_MODEL__LOOK_AHEAD, null, msgs);
      msgs = basicSetLookAhead(newLookAhead, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OmtPackage.OBJECT_MODEL__LOOK_AHEAD, newLookAhead, newLookAhead));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<OMTComponent> getOmtComponents()
  {
    if (omtComponents == null)
    {
      omtComponents = new EObjectContainmentEList<OMTComponent>(OMTComponent.class, this, OmtPackage.OBJECT_MODEL__OMT_COMPONENTS);
    }
    return omtComponents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION:
        return basicSetTimeRepresentation(null, msgs);
      case OmtPackage.OBJECT_MODEL__LOOK_AHEAD:
        return basicSetLookAhead(null, msgs);
      case OmtPackage.OBJECT_MODEL__OMT_COMPONENTS:
        return ((InternalEList<?>)getOmtComponents()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OmtPackage.OBJECT_MODEL__NAME:
        return getName();
      case OmtPackage.OBJECT_MODEL__VERSION:
        return getVersion();
      case OmtPackage.OBJECT_MODEL__TYPE:
        return getType();
      case OmtPackage.OBJECT_MODEL__PURPOSE:
        return getPurpose();
      case OmtPackage.OBJECT_MODEL__DOMAIN:
        return getDomain();
      case OmtPackage.OBJECT_MODEL__SPONSOR:
        return getSponsor();
      case OmtPackage.OBJECT_MODEL__POC_HONORIFIC:
        return getPocHonorific();
      case OmtPackage.OBJECT_MODEL__POC_FIRST_NAME:
        return getPocFirstName();
      case OmtPackage.OBJECT_MODEL__POC_LAST_NAME:
        return getPocLastName();
      case OmtPackage.OBJECT_MODEL__POC_ORG_NAME:
        return getPocOrgName();
      case OmtPackage.OBJECT_MODEL__POC_PHONE:
        return getPocPhone();
      case OmtPackage.OBJECT_MODEL__POC_EMAIL:
        return getPocEmail();
      case OmtPackage.OBJECT_MODEL__MODIFICATION_DATE:
        return getModificationDate();
      case OmtPackage.OBJECT_MODEL__MOM_VERSION:
        return getMomVersion();
      case OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION:
        return getTimeRepresentation();
      case OmtPackage.OBJECT_MODEL__LOOK_AHEAD:
        return getLookAhead();
      case OmtPackage.OBJECT_MODEL__OMT_COMPONENTS:
        return getOmtComponents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OmtPackage.OBJECT_MODEL__NAME:
        setName((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__VERSION:
        setVersion((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__TYPE:
        setType((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__PURPOSE:
        setPurpose((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__DOMAIN:
        setDomain((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__SPONSOR:
        setSponsor((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__POC_HONORIFIC:
        setPocHonorific((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__POC_FIRST_NAME:
        setPocFirstName((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__POC_LAST_NAME:
        setPocLastName((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__POC_ORG_NAME:
        setPocOrgName((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__POC_PHONE:
        setPocPhone((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__POC_EMAIL:
        setPocEmail((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__MODIFICATION_DATE:
        setModificationDate((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__MOM_VERSION:
        setMomVersion((String)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION:
        setTimeRepresentation((TimeRepresentation)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__LOOK_AHEAD:
        setLookAhead((Lookahead)newValue);
        return;
      case OmtPackage.OBJECT_MODEL__OMT_COMPONENTS:
        getOmtComponents().clear();
        getOmtComponents().addAll((Collection<? extends OMTComponent>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OmtPackage.OBJECT_MODEL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__VERSION:
        setVersion(VERSION_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__PURPOSE:
        setPurpose(PURPOSE_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__DOMAIN:
        setDomain(DOMAIN_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__SPONSOR:
        setSponsor(SPONSOR_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__POC_HONORIFIC:
        setPocHonorific(POC_HONORIFIC_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__POC_FIRST_NAME:
        setPocFirstName(POC_FIRST_NAME_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__POC_LAST_NAME:
        setPocLastName(POC_LAST_NAME_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__POC_ORG_NAME:
        setPocOrgName(POC_ORG_NAME_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__POC_PHONE:
        setPocPhone(POC_PHONE_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__POC_EMAIL:
        setPocEmail(POC_EMAIL_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__MODIFICATION_DATE:
        setModificationDate(MODIFICATION_DATE_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__MOM_VERSION:
        setMomVersion(MOM_VERSION_EDEFAULT);
        return;
      case OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION:
        setTimeRepresentation((TimeRepresentation)null);
        return;
      case OmtPackage.OBJECT_MODEL__LOOK_AHEAD:
        setLookAhead((Lookahead)null);
        return;
      case OmtPackage.OBJECT_MODEL__OMT_COMPONENTS:
        getOmtComponents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OmtPackage.OBJECT_MODEL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case OmtPackage.OBJECT_MODEL__VERSION:
        return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
      case OmtPackage.OBJECT_MODEL__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case OmtPackage.OBJECT_MODEL__PURPOSE:
        return PURPOSE_EDEFAULT == null ? purpose != null : !PURPOSE_EDEFAULT.equals(purpose);
      case OmtPackage.OBJECT_MODEL__DOMAIN:
        return DOMAIN_EDEFAULT == null ? domain != null : !DOMAIN_EDEFAULT.equals(domain);
      case OmtPackage.OBJECT_MODEL__SPONSOR:
        return SPONSOR_EDEFAULT == null ? sponsor != null : !SPONSOR_EDEFAULT.equals(sponsor);
      case OmtPackage.OBJECT_MODEL__POC_HONORIFIC:
        return POC_HONORIFIC_EDEFAULT == null ? pocHonorific != null : !POC_HONORIFIC_EDEFAULT.equals(pocHonorific);
      case OmtPackage.OBJECT_MODEL__POC_FIRST_NAME:
        return POC_FIRST_NAME_EDEFAULT == null ? pocFirstName != null : !POC_FIRST_NAME_EDEFAULT.equals(pocFirstName);
      case OmtPackage.OBJECT_MODEL__POC_LAST_NAME:
        return POC_LAST_NAME_EDEFAULT == null ? pocLastName != null : !POC_LAST_NAME_EDEFAULT.equals(pocLastName);
      case OmtPackage.OBJECT_MODEL__POC_ORG_NAME:
        return POC_ORG_NAME_EDEFAULT == null ? pocOrgName != null : !POC_ORG_NAME_EDEFAULT.equals(pocOrgName);
      case OmtPackage.OBJECT_MODEL__POC_PHONE:
        return POC_PHONE_EDEFAULT == null ? pocPhone != null : !POC_PHONE_EDEFAULT.equals(pocPhone);
      case OmtPackage.OBJECT_MODEL__POC_EMAIL:
        return POC_EMAIL_EDEFAULT == null ? pocEmail != null : !POC_EMAIL_EDEFAULT.equals(pocEmail);
      case OmtPackage.OBJECT_MODEL__MODIFICATION_DATE:
        return MODIFICATION_DATE_EDEFAULT == null ? modificationDate != null : !MODIFICATION_DATE_EDEFAULT.equals(modificationDate);
      case OmtPackage.OBJECT_MODEL__MOM_VERSION:
        return MOM_VERSION_EDEFAULT == null ? momVersion != null : !MOM_VERSION_EDEFAULT.equals(momVersion);
      case OmtPackage.OBJECT_MODEL__TIME_REPRESENTATION:
        return timeRepresentation != null;
      case OmtPackage.OBJECT_MODEL__LOOK_AHEAD:
        return lookAhead != null;
      case OmtPackage.OBJECT_MODEL__OMT_COMPONENTS:
        return omtComponents != null && !omtComponents.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", version: ");
    result.append(version);
    result.append(", type: ");
    result.append(type);
    result.append(", purpose: ");
    result.append(purpose);
    result.append(", domain: ");
    result.append(domain);
    result.append(", sponsor: ");
    result.append(sponsor);
    result.append(", pocHonorific: ");
    result.append(pocHonorific);
    result.append(", pocFirstName: ");
    result.append(pocFirstName);
    result.append(", pocLastName: ");
    result.append(pocLastName);
    result.append(", pocOrgName: ");
    result.append(pocOrgName);
    result.append(", pocPhone: ");
    result.append(pocPhone);
    result.append(", pocEmail: ");
    result.append(pocEmail);
    result.append(", modificationDate: ");
    result.append(modificationDate);
    result.append(", momVersion: ");
    result.append(momVersion);
    result.append(')');
    return result.toString();
  }

} //ObjectModelImpl
