/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.ui.contentassist;

import com.cohesionforce.hla.dsl.ui.contentassist.AbstractOmtProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OmtProposalProvider extends AbstractOmtProposalProvider {
}
