/*
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.validation

import com.cohesionforce.hla.dsl.fom.AttributeClass
import com.cohesionforce.hla.dsl.fom.FomPackage
import java.util.ArrayList
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class FomValidator extends AbstractFomValidator {

	var names = new ArrayList<String>
	var childNames = new ArrayList<String>
	
	public static val INVALID_NAME = 'invalidName'
	public static val DUPLICATE_CHILD = 'duplicateChild'

	/*
	 * Check to make sure that the same attribute is not used more than once in an attribute class
	 */
	@Check
	def checkUniqueParameters(AttributeClass attributeClass) {
		names.clear
		attributeClass.attributes.forEach[{
			if(it.ref !== null && it.ref.name !== null) {
				if(names.contains(it.ref.name)) {
					error('Duplicate parameters with name: '+it.ref.name, 
						FomPackage.Literals.ATTRIBUTE_CLASS__ATTRIBUTES,
						INVALID_NAME
					)
				} else {
					names.add(it.ref.name)
				}
			}
		}]
	}
	
	/*
	 * Make sure that child classes of an Attribute class have unique names
	 */
	@Check
	def checkUniqueChildClasses(AttributeClass attributeClass) {
		childNames.clear
		attributeClass.classes.forEach[{
			if(it.ref !== null) {
				if(childNames.contains(it.ref.name)) {
					error('Duplicate parameters with name: '+it.ref.name, 
						FomPackage.Literals.ATTRIBUTE_CLASS__CLASSES,
						DUPLICATE_CHILD
					)
				} else {
					childNames.add(it.ref.name)
				}
			}
		}]
	}
	
	
}
