/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl;

import com.cohesionforce.hla.dsl.FomStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FomStandaloneSetup extends FomStandaloneSetupGenerated {
  public static void doSetup() {
    new FomStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
