/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.ide;

import com.cohesionforce.hla.dsl.FomRuntimeModule;
import com.cohesionforce.hla.dsl.FomStandaloneSetup;
import com.cohesionforce.hla.dsl.ide.FomIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FomIdeSetup extends FomStandaloneSetup {
  @Override
  public Injector createInjector() {
    FomRuntimeModule _fomRuntimeModule = new FomRuntimeModule();
    FomIdeModule _fomIdeModule = new FomIdeModule();
    return Guice.createInjector(Modules2.mixin(_fomRuntimeModule, _fomIdeModule));
  }
}
