/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.validation;

import com.cohesionforce.hla.dsl.validation.AbstractOmtValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OmtValidator extends AbstractOmtValidator {
}
