/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.fom;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttributeClass()
 * @model
 * @generated
 */
public interface AttributeClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttributeClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link com.cohesionforce.hla.dsl.fom.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttributeClass_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link com.cohesionforce.hla.dsl.fom.AttributeClass}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttributeClass_Classes()
   * @model containment="true"
   * @generated
   */
  EList<AttributeClass> getClasses();

} // AttributeClass
