/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.fom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.Attribute#getName <em>Name</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.Attribute#getTransport <em>Transport</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.Attribute#getOrder <em>Order</em>}</li>
 *   <li>{@link com.cohesionforce.hla.dsl.fom.Attribute#getSpace <em>Space</em>}</li>
 * </ul>
 *
 * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.fom.Attribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Transport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transport</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transport</em>' attribute.
   * @see #setTransport(String)
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttribute_Transport()
   * @model
   * @generated
   */
  String getTransport();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.fom.Attribute#getTransport <em>Transport</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transport</em>' attribute.
   * @see #getTransport()
   * @generated
   */
  void setTransport(String value);

  /**
   * Returns the value of the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Order</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' attribute.
   * @see #setOrder(String)
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttribute_Order()
   * @model
   * @generated
   */
  String getOrder();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.fom.Attribute#getOrder <em>Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' attribute.
   * @see #getOrder()
   * @generated
   */
  void setOrder(String value);

  /**
   * Returns the value of the '<em><b>Space</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Space</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Space</em>' reference.
   * @see #setSpace(Space)
   * @see com.cohesionforce.hla.dsl.fom.FomPackage#getAttribute_Space()
   * @model
   * @generated
   */
  Space getSpace();

  /**
   * Sets the value of the '{@link com.cohesionforce.hla.dsl.fom.Attribute#getSpace <em>Space</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Space</em>' reference.
   * @see #getSpace()
   * @generated
   */
  void setSpace(Space value);

} // Attribute
