/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.fom;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.cohesionforce.hla.dsl.fom.FomFactory
 * @model kind="package"
 * @generated
 */
public interface FomPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fom";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.cohesionforce.com/hla/dsl/Fom";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fom";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FomPackage eINSTANCE = com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl.init();

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.FedImpl <em>Fed</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.FedImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getFed()
   * @generated
   */
  int FED = 0;

  /**
   * The feature id for the '<em><b>Federation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FED__FEDERATION = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FED__VERSION = 1;

  /**
   * The feature id for the '<em><b>Spaces</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FED__SPACES = 2;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FED__CLASSES = 3;

  /**
   * The number of structural features of the '<em>Fed</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FED_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.FederationImpl <em>Federation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.FederationImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getFederation()
   * @generated
   */
  int FEDERATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEDERATION__NAME = 0;

  /**
   * The number of structural features of the '<em>Federation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEDERATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.FEDversionImpl <em>FE Dversion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.FEDversionImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getFEDversion()
   * @generated
   */
  int FE_DVERSION = 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FE_DVERSION__VERSION = 0;

  /**
   * The number of structural features of the '<em>FE Dversion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FE_DVERSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.SpaceImpl <em>Space</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.SpaceImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getSpace()
   * @generated
   */
  int SPACE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPACE__NAME = 0;

  /**
   * The feature id for the '<em><b>Dimensions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPACE__DIMENSIONS = 1;

  /**
   * The number of structural features of the '<em>Space</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPACE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.DimensionImpl <em>Dimension</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.DimensionImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getDimension()
   * @generated
   */
  int DIMENSION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Dimension</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.AttributeClassImpl <em>Attribute Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.AttributeClassImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getAttributeClass()
   * @generated
   */
  int ATTRIBUTE_CLASS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CLASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CLASS__ATTRIBUTES = 1;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CLASS__CLASSES = 2;

  /**
   * The number of structural features of the '<em>Attribute Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CLASS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.AttributeImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Transport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TRANSPORT = 1;

  /**
   * The feature id for the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ORDER = 2;

  /**
   * The feature id for the '<em><b>Space</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__SPACE = 3;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.InteractionClassImpl <em>Interaction Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.InteractionClassImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getInteractionClass()
   * @generated
   */
  int INTERACTION_CLASS = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Transport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS__TRANSPORT = 1;

  /**
   * The feature id for the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS__ORDER = 2;

  /**
   * The feature id for the '<em><b>Space</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS__SPACE = 3;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS__PARAMETERS = 4;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS__CLASSES = 5;

  /**
   * The number of structural features of the '<em>Interaction Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_CLASS_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link com.cohesionforce.hla.dsl.fom.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.cohesionforce.hla.dsl.fom.impl.ParameterImpl
   * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.Fed <em>Fed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fed</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Fed
   * @generated
   */
  EClass getFed();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.hla.dsl.fom.Fed#getFederation <em>Federation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Federation</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Fed#getFederation()
   * @see #getFed()
   * @generated
   */
  EReference getFed_Federation();

  /**
   * Returns the meta object for the containment reference '{@link com.cohesionforce.hla.dsl.fom.Fed#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Version</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Fed#getVersion()
   * @see #getFed()
   * @generated
   */
  EReference getFed_Version();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.Fed#getSpaces <em>Spaces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Spaces</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Fed#getSpaces()
   * @see #getFed()
   * @generated
   */
  EReference getFed_Spaces();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.Fed#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Fed#getClasses()
   * @see #getFed()
   * @generated
   */
  EReference getFed_Classes();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.Federation <em>Federation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Federation</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Federation
   * @generated
   */
  EClass getFederation();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Federation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Federation#getName()
   * @see #getFederation()
   * @generated
   */
  EAttribute getFederation_Name();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.FEDversion <em>FE Dversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FE Dversion</em>'.
   * @see com.cohesionforce.hla.dsl.fom.FEDversion
   * @generated
   */
  EClass getFEDversion();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.FEDversion#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see com.cohesionforce.hla.dsl.fom.FEDversion#getVersion()
   * @see #getFEDversion()
   * @generated
   */
  EAttribute getFEDversion_Version();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.Space <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Space</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Space
   * @generated
   */
  EClass getSpace();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Space#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Space#getName()
   * @see #getSpace()
   * @generated
   */
  EAttribute getSpace_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.Space#getDimensions <em>Dimensions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dimensions</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Space#getDimensions()
   * @see #getSpace()
   * @generated
   */
  EReference getSpace_Dimensions();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.Dimension <em>Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dimension</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Dimension
   * @generated
   */
  EClass getDimension();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Dimension#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Dimension#getName()
   * @see #getDimension()
   * @generated
   */
  EAttribute getDimension_Name();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.AttributeClass <em>Attribute Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Class</em>'.
   * @see com.cohesionforce.hla.dsl.fom.AttributeClass
   * @generated
   */
  EClass getAttributeClass();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.AttributeClass#getName()
   * @see #getAttributeClass()
   * @generated
   */
  EAttribute getAttributeClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see com.cohesionforce.hla.dsl.fom.AttributeClass#getAttributes()
   * @see #getAttributeClass()
   * @generated
   */
  EReference getAttributeClass_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.AttributeClass#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see com.cohesionforce.hla.dsl.fom.AttributeClass#getClasses()
   * @see #getAttributeClass()
   * @generated
   */
  EReference getAttributeClass_Classes();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Attribute#getTransport <em>Transport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Transport</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Attribute#getTransport()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Transport();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Attribute#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Order</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Attribute#getOrder()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Order();

  /**
   * Returns the meta object for the reference '{@link com.cohesionforce.hla.dsl.fom.Attribute#getSpace <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Space</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Attribute#getSpace()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Space();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.InteractionClass <em>Interaction Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction Class</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass
   * @generated
   */
  EClass getInteractionClass();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.InteractionClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass#getName()
   * @see #getInteractionClass()
   * @generated
   */
  EAttribute getInteractionClass_Name();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.InteractionClass#getTransport <em>Transport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Transport</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass#getTransport()
   * @see #getInteractionClass()
   * @generated
   */
  EAttribute getInteractionClass_Transport();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.InteractionClass#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Order</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass#getOrder()
   * @see #getInteractionClass()
   * @generated
   */
  EAttribute getInteractionClass_Order();

  /**
   * Returns the meta object for the reference '{@link com.cohesionforce.hla.dsl.fom.InteractionClass#getSpace <em>Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Space</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass#getSpace()
   * @see #getInteractionClass()
   * @generated
   */
  EReference getInteractionClass_Space();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.InteractionClass#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass#getParameters()
   * @see #getInteractionClass()
   * @generated
   */
  EReference getInteractionClass_Parameters();

  /**
   * Returns the meta object for the containment reference list '{@link com.cohesionforce.hla.dsl.fom.InteractionClass#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see com.cohesionforce.hla.dsl.fom.InteractionClass#getClasses()
   * @see #getInteractionClass()
   * @generated
   */
  EReference getInteractionClass_Classes();

  /**
   * Returns the meta object for class '{@link com.cohesionforce.hla.dsl.fom.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link com.cohesionforce.hla.dsl.fom.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.cohesionforce.hla.dsl.fom.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FomFactory getFomFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.FedImpl <em>Fed</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.FedImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getFed()
     * @generated
     */
    EClass FED = eINSTANCE.getFed();

    /**
     * The meta object literal for the '<em><b>Federation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FED__FEDERATION = eINSTANCE.getFed_Federation();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FED__VERSION = eINSTANCE.getFed_Version();

    /**
     * The meta object literal for the '<em><b>Spaces</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FED__SPACES = eINSTANCE.getFed_Spaces();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FED__CLASSES = eINSTANCE.getFed_Classes();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.FederationImpl <em>Federation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.FederationImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getFederation()
     * @generated
     */
    EClass FEDERATION = eINSTANCE.getFederation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEDERATION__NAME = eINSTANCE.getFederation_Name();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.FEDversionImpl <em>FE Dversion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.FEDversionImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getFEDversion()
     * @generated
     */
    EClass FE_DVERSION = eINSTANCE.getFEDversion();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FE_DVERSION__VERSION = eINSTANCE.getFEDversion_Version();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.SpaceImpl <em>Space</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.SpaceImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getSpace()
     * @generated
     */
    EClass SPACE = eINSTANCE.getSpace();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPACE__NAME = eINSTANCE.getSpace_Name();

    /**
     * The meta object literal for the '<em><b>Dimensions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPACE__DIMENSIONS = eINSTANCE.getSpace_Dimensions();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.DimensionImpl <em>Dimension</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.DimensionImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getDimension()
     * @generated
     */
    EClass DIMENSION = eINSTANCE.getDimension();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIMENSION__NAME = eINSTANCE.getDimension_Name();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.AttributeClassImpl <em>Attribute Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.AttributeClassImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getAttributeClass()
     * @generated
     */
    EClass ATTRIBUTE_CLASS = eINSTANCE.getAttributeClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_CLASS__NAME = eINSTANCE.getAttributeClass_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_CLASS__ATTRIBUTES = eINSTANCE.getAttributeClass_Attributes();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_CLASS__CLASSES = eINSTANCE.getAttributeClass_Classes();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.AttributeImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Transport</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__TRANSPORT = eINSTANCE.getAttribute_Transport();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ORDER = eINSTANCE.getAttribute_Order();

    /**
     * The meta object literal for the '<em><b>Space</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__SPACE = eINSTANCE.getAttribute_Space();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.InteractionClassImpl <em>Interaction Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.InteractionClassImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getInteractionClass()
     * @generated
     */
    EClass INTERACTION_CLASS = eINSTANCE.getInteractionClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION_CLASS__NAME = eINSTANCE.getInteractionClass_Name();

    /**
     * The meta object literal for the '<em><b>Transport</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION_CLASS__TRANSPORT = eINSTANCE.getInteractionClass_Transport();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION_CLASS__ORDER = eINSTANCE.getInteractionClass_Order();

    /**
     * The meta object literal for the '<em><b>Space</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION_CLASS__SPACE = eINSTANCE.getInteractionClass_Space();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION_CLASS__PARAMETERS = eINSTANCE.getInteractionClass_Parameters();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION_CLASS__CLASSES = eINSTANCE.getInteractionClass_Classes();

    /**
     * The meta object literal for the '{@link com.cohesionforce.hla.dsl.fom.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.cohesionforce.hla.dsl.fom.impl.ParameterImpl
     * @see com.cohesionforce.hla.dsl.fom.impl.FomPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

  }

} //FomPackage
