/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.ide;

import com.cohesionforce.hla.dsl.ide.AbstractOmtIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class OmtIdeModule extends AbstractOmtIdeModule {
}
