/*
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.ide

import com.cohesionforce.hla.dsl.FomRuntimeModule
import com.cohesionforce.hla.dsl.FomStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FomIdeSetup extends FomStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FomRuntimeModule, new FomIdeModule))
	}
	
}
