/**
 * generated by Xtext 2.12.0
 */
package com.cohesionforce.hla.dsl.ui;

import com.cohesionforce.hla.dsl.ui.AbstractOmtUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OmtUiModule extends AbstractOmtUiModule {
  public OmtUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
